.old/portfolio/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.all_blogs, name="all_blogs"),
    path("<int:blog_id>", views.detail, name="details"),
]

.old/portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls.static import static

from django.conf import settings
from portofolio_app import views
from django.urls import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("blog/", include("blog.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

.old/portfolio/blog/models.py
from django.db import models

# Create your models here.


class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    fecha = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"Title: {self.title}"

.old/portfolio/portofolio_app/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    tittle = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to="img")
    url = models.URLField(max_length=200, blank=True)

.old/portfolio/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

# Create your views here.


def all_blogs(request):

    return render(
        request,
        "index-blog.html",
        context={"blogs": Blog.objects.all().order_by("fecha")},
    )


def detail(request, blog_id):

    blog = get_object_or_404(Blog, pk=blog_id)

    return render(request, "details-blog.html", {"blog": blog})

.old/portfolio/portofolio_app/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.


def home(request):
    return render(
        request,
        "home.html",
        context={"projects": Project.objects.all()},
    )

.old/portfolio/portofolio_app/templates/bootstrap/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static "portfolio/Logo.png" %}">

  <link rel={% static "styles" %} href="main.css">
  <title>Sergio París</title>
</head>

<body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static "img/Logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="Nick's Logo">
        <span>Sergio París</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center align-items-center" id="navbarNav">
        <ul class="navbar-nav ml-auto ">
          <li class="nav-item">
            <a class="nav-link" href="{% static "portfolio/resume.pdf" %}">Resume</a>
          </li>
          <li>
            <a role="button" href="{% url 'blog:all_blogs' %}" class="btn btn-primary">Blog</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

.old/portfolio/portofolio_app/templates/home.html
{% extends "bootstrap/base.html" %}

{% load static %}

{% block content %}
<style>
  div .img-projects{
    width: 350px;
    height: 250px
  }
</style>
<div class="row justify-content-center my-3">
  <div class="col-5">
    <img src="{% static 'img/sora.webp' %}" class="img-fluid">
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold">Sergio is a student of web aplication developer from the IES SANCLEMENTE 😊</h1>
  </div>
</div>

<h2 class="mt-5">Portfolio</h2>
<hr>
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">

    {% if project.url %}
    <a href="{{ project.url }}">
      <img  src="{{ project.image.url }}" class="img-fluid mb-2 img-projects">
    </a>
    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-2 img-projects">
    {% endif %}
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>

  </div>
  {% endfor %}
</div>

{% endblock %}

.old/portfolio/portofolio_app/templates/index-portfolio.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Document</title>
	</head>
	<body>
		<h1>Welcome</h1>
		<a href={%url "blog:all_blogs" %}>Blogs</a><br>
		{% for project in projects %}
            <h2>{{project.tittle}}</h2><br>
            <p>{{project.description}}</p>
            <img src="{{project.image.url}}" width="50" heigth="50" /><br />
            {% if project.url %}
                <a href="{{project.url}}">link</a>
            {% endif %} 
        {% endfor %}
	</body>
</html>