code/satisfactory/apps/calculators/urls.py
from django.urls import path, include

from . import views

app_name = "calculator"

urlpatterns = [
    path("list/", views.CalculatorList.as_view(), name="list"),
    path("energy/", views.EnergyCalculator.as_view(), name="energy"),
    path("resources/", views.ResourcesCalculator.as_view(), name="resources"),
]

code/satisfactory/apps/objects/urls.py
from django.urls import path, include  # type:ignore

from . import views
from .forms import urls
from .recipesForm import urls as rec_urls


app_name = "objects"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("list/", views.ObjectsList.as_view(), name="list"),
    path("details/<int:pk>", views.DetailsView.as_view(), name="details"),
    path("process/marker/", views.ProcessMarker.as_view(), name="process_marker"),
    # I MADE AN FOLD/MODULE TO SAVE ALL THE FORMS INFORMATION, LIKE URLS AND VIEWS
    path("forms/", include(urls)),
    path("recipes/<int:pk>/", views.RecipeView.as_view(), name="recipe"),
    path("recipes/modify/", include(rec_urls)),
]

code/satisfactory/satisfactory/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.api import urls as api_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include(api_urls)),
    path("calculator/", include("apps.calculators.urls")),
    path("", include("apps.objects.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

code/satisfactory/templates/components/header.html
<header>
    <section>
        <a href="{% url "objects:home" %}">

            <img src="" alt="Logo">
            <span>Texto</span>
        </a>
    </section>
    <nav>
        <ul>
            <li><a href="{% url "objects:home" %}">Home</a></li>
            <li><a href="{% url "objects:list" %}">Resources</a></li>
            <li><a href="{% url "calculator:list" %}">Calculators</a></li>
        </ul>
    </nav>
</header>