code.temp/01-adding-templates/apps/reviews/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.ReviewView.as_view()),
    path("thank-you", views.ThankYouView.as_view()),
    path("reviews/", views.ReviewListView.as_view()),
    path("review/<int:pk>", views.SingleReviewView.as_view()),
]

code.temp/01-adding-templates/apps/students/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "students"

urlpatterns = [
    path("", views.StudentListView.as_view(), name="list"),
    path("register/", views.StudentRegisterView.as_view()),
    path("delete/<int:pk>/", views.StudentDeleteView.as_view(), name="delete"),
    path("update/<int:pk>/", views.StudentUpdateView.as_view(), name="update"),
]

code.temp/01-adding-templates/feedback/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from apps.reviews import urls as rurls
from apps.students import urls as surls


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(rurls)),
    path("students/", include(surls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

code.temp/01-adding-templates/apps/reviews/models.py
from django.db import models

# Create your models here.


class Review(models.Model):
    user_name = models.CharField(max_length=100)
    review_text = models.TextField()
    rating = models.IntegerField()

    def __str__(self):
        return f"{self.id}-{self.user_name}"

code.temp/01-adding-templates/apps/students/models.py
from django.db import models

# Create your models here.


class Student(models.Model):
    name = models.CharField(max_length=200)
    degree = models.CharField(max_length=100)

code.temp/01-adding-templates/apps/reviews/forms.py
from django import forms

from .models import Review

# class ReviewForm(forms.Form):
#     user_name = forms.CharField(label="Your Name", max_length=100, error_messages={
#         "required": "Your name must not be empty!",
#         "max_length": "Please enter a shorter name!"
#     })
#     review_text = forms.CharField(label="Your Feedback", widget=forms.Textarea, max_length=200)
#     rating = forms.IntegerField(label="Your Rating", min_value=1, max_value=5)


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = "__all__"
        # exclude = ['owner_comment']
        labels = {
            "user_name": "Your Name",
            "review_text": "Your Feedback",
            "rating": "Your Rating"
        }
        error_messages = {
            "user_name": {
              "required": "Your name must not be empty!",
              "max_length": "Please enter a shorter name!"
            }
        }

code.temp/01-adding-templates/apps/students/forms.py
from django import forms

from .models import Student


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = "__all__"

code.temp/01-adding-templates/apps/reviews/views.py
from .models import Review
from django.http import HttpResponseRedirect  # type:ignore
from django.shortcuts import render  # type:ignore
from django.views import View  # type:ignore
from django.views.generic.base import TemplateView  # type:ignore
from django.views.generic import ListView, DetailView  # type:ignore
from django.views.generic.edit import FormView  # type:ignore
from .forms import ReviewForm  # type:ignore

# Create your views here.


class ReviewView(FormView):

    form_class = ReviewForm
    template_name = "reviews/review.html"
    success_url = "/thank-you"

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


# with VIEW asecas
# def get(self, request):
# form = ReviewForm()
#
# return render(request, "reviews/review.html", {"form": form})
#
# def post(self, request):
# form = ReviewForm(request.POST)
#
# if form.is_valid():
# form.save()
# return HttpResponseRedirect("/thank-you")
#
# return render(request, "reviews/review.html", {"form": form})


def thank_you(request):
    return render(request, "reviews/thank_you.html")


class ThankYouView(TemplateView):
    template_name = "reviews/thank_you.html"

    def get_context_data(self, **kwargs) -> dict[str, any]:
        context = super().get_context_data(**kwargs)
        context["message"] = "This works!"
        return context


class ReviewListView(ListView):
    template_name = "reviews/review_list.html"
    model = Review
    context_object_name = "reviews"


class SingleReviewView(DetailView):
    template_name = "reviews/single_review.html"
    model = Review
    # context_object_name = "reviews"

code.temp/01-adding-templates/apps/students/views.py
from django.shortcuts import render

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from django.urls import reverse_lazy

from .models import Student
from .forms import StudentForm

# Create your views here.


class StudentRegisterView(CreateView):
    model = Student
    form_class = StudentForm
    template_name = "students/register.html"
    success_url = "/students"


class StudentDeleteView(DeleteView):
    model = Student
    template_name = "students/delete.html"
    success_url = reverse_lazy("students:list")


class StudentUpdateView(UpdateView):
    model = Student
    form_class = StudentForm
    template_name = "students/update.html"
    template_name_suffix = "update_form"

    success_url = reverse_lazy("students:list")


class StudentListView(ListView):
    model = Student
    template_name = "students/list.html"
    context_object_name = "students"

code.temp/01-adding-templates/apps/students/templates/students/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block title %}
    {% endblock %}
  </title>
  <link rel="stylesheet" href="{% static "reviews/styles.css" %}">
</head>
<body>
  {% block content %}
  {% endblock %}
</body>
</html>

code.temp/01-adding-templates/apps/students/templates/students/delete.html
{% extends "students/base.html" %}

{% block title %}Listado{% endblock title %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        {{object}}
        {{ form.as_p }}
        <input type="submit" value="Confirm">
    </form>
{% endblock content %}

code.temp/01-adding-templates/apps/students/templates/students/list.html
{% extends "students/base.html" %}

{% block title %}Listado{% endblock title %}

{% block content %}

{% for student in students %}

<article>
    {{student.name}}
    {{student.degree}}
    <a href={% url "students:delete" student.id %}><button>Delete</button></a>
    <a href={% url "students:update" student.id %}><button>Update</button></a>
</article>

{% endfor %}

{% endblock content %}

code.temp/01-adding-templates/apps/students/templates/students/register.html
{% extends "students/base.html" %}

{% block title %}Listado{% endblock title %}


{% block content %}
    <form action="/students/register/" method="post">
        {% csrf_token %}
        {{form}}
    
        <input type="submit">
    </form>
{% endblock content %}

code.temp/01-adding-templates/apps/students/templates/students/update.html
{% extends "students/base.html" %}

{% block title %}Listado{% endblock title %}


{% block content %}
    <form  method="post">
        {% csrf_token %}
        {{form}}
    
        <input type="Send data">
    </form>
    
{% endblock content %}