code/satisfactory/apps/objects/urls.py
from django.urls import path, include  # type:ignore

from . import views
from .forms import urls
from .recipesForm import urls as rec_urls


app_name = "objects"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("list/", views.ObjectsList.as_view(), name="list"),
    path("details/<int:pk>", views.DetailsView.as_view(), name="details"),
    path("process/marker/", views.ProcessMarker.as_view(), name="process_marker"),
    # I MADE AN FOLD/MODULE TO SAVE ALL THE FORMS INFORMATION, LIKE URLS AND VIEWS
    path("forms/", include(urls)),
    path("recipes/<int:pk>/", views.RecipeView.as_view(), name="recipe"),
    path("recipes/modify/", include(rec_urls)),
]

code/satisfactory/satisfactory/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.api import urls as api_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include(api_urls)),
    path("calculator/", include("apps.calculators.urls")),
    path("", include("apps.objects.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

code/satisfactory/templates/apps/objects_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Resources List{% endblock title %}


{% block scripts %}
<script src="{% static "scripts/filterMarkers.js" %}" defer></script>
{% endblock scripts %}

{% block styles %}
<link rel="stylesheet" href="{% static "styles/resourceList.css" %}">

{% endblock styles %}

{% block content %}

<h1>Resources list</h1>
{{markers}}
<select name="filter" id="resourceFilter">
    <option value="false" selected>All</option>
    <option value="true">Markers</option>
</select>
<section id="list">
    {% for resource in resources %}
    <a href="{% url "objects:details" resource.id %}" 
    {% if resource.id in markers %}
    data-marked="true"
    {% else %}
    data-marked="false"
    {% endif %}
    >
            <article>
                <h2>{{resource.name}}</h2>
                <img src="{{resource.img.url}}" alt="Imaxen de {{resource.name}}">
            </article>
        </a>

        {% endfor %}
</section>

<a href="{% url "objects:forms:create" %}"><button>Add new resource</button></a>

{% endblock content %}